'use strict';

/**
 * CHES supplier service and warranty desks (Australia).
 *
 * Source: the CHES supplier service & warranty contact list, updated
 * 2 September 2026. Keep this file as the record of what CHES was told, and
 * edit live entries in the console — the seed only fills gaps, it never
 * overwrites an address someone has corrected.
 *
 * `defaultWarrantyMonths` is filled in ONLY where the supplier states one
 * unambiguous period for its ordinary range. Where cover varies by model it is
 * left null on purpose: a wrong default silently sets a wrong expiry on real
 * equipment, and "confirm by model" is the honest answer. In every case the
 * warranty stated on the invoice wins over this.
 *
 * `aliases` are the brands that reach this desk, because the name on the
 * machine is often not the name of the company that services it.
 */

const SUPPLIERS = [
  {
    name: 'B+S',
    serviceEmail: 'clientservices@bscommercialkitchens.com',
    ccEmail: 'spareparts@bscommercialkitchens.com',
    portalUrl: 'https://bscommercialkitchens.com/request-a-warranty-service-call-2/',
    phone: '03 9469 4754',
    aliases: ['B+S', 'B&S', 'BS Commercial', 'K+', 'Black', 'Rapid', 'SCooker', 'Verro'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'K+ 18 months; Black 24; Rapid 24; SCooker 24. The service-call page shows Verro 36 while another B+S page shows 24 — confirm against the order terms.',
    notes: 'Email or the warranty form is preferred over phoning.',
  },
  {
    name: 'Birko / Zip',
    serviceEmail: 'services@zipwater.com',
    portalUrl: 'https://www.zipwater.com/book-a-service',
    phone: '1800 460 222',
    aliases: ['Birko', 'Zip', 'Zip Water'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Varies by product and model — check the manual or invoice.',
    notes: 'Have the serial number and proof of purchase ready.',
  },
  {
    name: 'Bromic',
    serviceEmail: 'service@bromic.com',
    portalUrl: 'https://booking.mendrhub.com/?tenantid=ca54bc84-448c-44d6-8625-60853b6fd8c0&tid=13101219-4e99-4aa1-9184-7560dd1bc280',
    phone: '02 9426 5222',
    aliases: ['Bromic'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Varies across refrigeration, ice, heating and cooking ranges.',
    notes: 'Email or form preferred. Card details may be required.',
  },
  {
    name: 'CMT (Coffee Machine Technologies)',
    serviceEmail: 'ops@coffeemachinetechnologies.com.au',
    ccEmail: 'info@coffeemachinetechnologies.com.au',
    portalUrl: 'https://coffeemachinetechnologies.com.au/service/',
    phone: 'Head office / service 03 9335 2293 · Sydney 0420 680 861',
    aliases: ['CMT', 'Coffee Machine Technologies'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Multi-brand coffee equipment — use the applicable brand, model and invoice terms.',
    notes: 'Direct contact: dino@coffeemachinetechnologies.com.au',
  },
  {
    name: 'Comcater',
    serviceEmail: 'service@comcater.com.au',
    ccEmail: 'contactus@comcater.com.au',
    portalUrl: 'https://www.comcater.com.au/service/',
    phone: '1800 810 161',
    aliases: ['Comcater', 'Rational', 'Mareno', 'Tecnomac', 'Trueheat', 'True Heat', 'Brema', 'Comenda', 'PureVac', 'Mibrasa', 'Frymaster'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Most brands 12 parts / 12 labour. Rational, Mareno, Tecnomac and Trueheat 24/24; Brema 36/36; Comenda 24 parts / 12 labour; PureVac 36 parts / 24 labour; Mibrasa 24 parts / 12 labour. Frymaster varies by series and component.',
    notes: '',
  },
  {
    name: 'FSM',
    serviceEmail: 'service@fsm-pl.com.au',
    portalUrl: 'https://fsm-pl.com.au/book-a-service/',
    phone: '03 8645 2555',
    aliases: ['FSM'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Distributes multiple brands — confirm by brand and model.',
    notes: 'Submit model, serial number, invoice and fault details.',
  },
  {
    name: 'Hoshizaki',
    serviceEmail: 'lancerservice@lancerworldwide.com',
    portalUrl: 'https://hoshizaki.com.au/warranty-request/',
    phone: '1300 551 361',
    aliases: ['Hoshizaki', 'Lancer'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'KM / KMD / IM ice machines 36 whole unit; FM / DCM and refrigeration 24; DB dispensers 24; bins and sushi cabinets 12. Some components run longer, and eligible registration may extend cover.',
    notes: '',
  },
  {
    name: 'ICE (International Catering Equipment)',
    serviceEmail: 'tracey@internationalcatering.com.au',
    ccEmail: 'parts@internationalcatering.com.au',
    portalUrl: 'https://www.internationalcatering.com.au/warranty-claim/',
    phone: '02 8372 0800',
    aliases: ['ICE', 'International Catering'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Distributes multiple brands — use the manufacturer, model or quotation terms.',
    notes: '',
  },
  {
    name: 'Meiko',
    serviceEmail: 'service@meiko.com.au',
    ccEmail: 'gmo@meiko.com.au',
    portalUrl: 'https://www.meiko.com/en-au/service/book-a-service',
    phone: '1300 562 500',
    aliases: ['Meiko', 'UPster'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Warewashing 24 months WHEN REGISTERED WITHIN 90 DAYS, otherwise shorter; other products generally 12. Full parts and labour within 100 km of a listed service centre — beyond that, year two is parts only.',
    notes: 'Registration within 90 days is what earns the second year. gmo@meiko.com.au is Monica Galang.',
  },
  {
    name: 'Middleby',
    serviceEmail: 'service@middleby.com.au',
    portalUrl: 'https://booking.mendrhub.com/?tenantid=13101219-4e99-4aa1-9184-7560dd1bc280&tid=3cf0b526-5f86-42d8-815b-2ad22f0ce67a',
    phone: '1800 013 123 · 02 9604 7333',
    aliases: ['Middleby'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Multi-brand portfolio — check the manual, quotation or warranty schedule.',
    notes: '',
  },
  {
    name: 'Moffat',
    serviceEmail: 'callcentre@moffat.com.au',
    portalUrl: 'https://www.moffat.com.au/lodge-service-booking-form',
    phone: '1300 264 217',
    aliases: ['Moffat', 'Waldorf', 'Turbofan', 'Washtech', 'Bonnet'],
    defaultWarrantyMonths: 24,
    warrantyNotes: 'Orders placed on or after 1 Sep 2024: 24 months from dispatch. Earlier orders: 12. Exceptions — selected Scotsman 36, Washtech cabinet parts 60, reusable health products 12. Spare parts 3.',
    notes: 'Submit by email OR the website form, not both.',
  },
  {
    name: 'Panasonic / Hussmann',
    serviceEmail: 'warranty.aus@hussmann.com',
    ccEmail: 'support.au@hussmann.com',
    portalUrl: 'https://hussmann.com.au/support/warranty/',
    phone: '02 8805 0440',
    aliases: ['Panasonic', 'Hussmann'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Check the quotation, invoice, project contract or model documentation.',
    notes: 'Email preferred.',
  },
  {
    name: 'Roband',
    serviceEmail: 'warranty@roband.com.au',
    ccEmail: 'spares@roband.com.au',
    portalUrl: 'https://www.roband.com.au/warranty-request/',
    phone: '1800 268 848',
    aliases: ['Roband', 'Robalec', 'Dipo', 'Robatherm', 'Noaw', 'Austheat', 'Hallde'],
    defaultWarrantyMonths: 12,
    warrantyNotes: 'Roband / Robalec / Dipo / Robatherm 12/12. Noaw 24/24. Austheat 12 labour, 24 parts, 60 tank after registration. Hallde 12/12, extendable to 36/36 if registered within 30 days. Selected microwaves 24 parts / 12 labour.',
    notes: 'Direct contact: duncan.mckenzie@roband.com.au',
  },
  {
    name: 'Robot Coupe',
    serviceEmail: 'services@robotcoupe.com.au',
    portalUrl: 'https://robotcoupe.au/',
    phone: '1800 762 682 · 02 9478 0300',
    aliases: ['Robot Coupe'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Usually return to base — verify the exact period in the manual or invoice.',
    notes: 'Where card details are required, the customer should book directly.',
  },
  {
    name: 'Scots Ice',
    serviceEmail: 'service@scotsice.com.au',
    portalUrl: 'https://www.scotsice.com.au/service/warranty-request/',
    phone: '1800 222 460 · 02 9684 5666',
    aliases: ['Scots Ice', 'Scotsice'],
    defaultWarrantyMonths: 12,
    warrantyNotes: 'Standard 12/12. CS and CS ZP cubers 24 parts / 12 labour; M-series 24/24; flakers, nugget and dispensers 12/12; storage and dispenser bins carry no stated warranty.',
    notes: 'Cleaning and maintenance records matter to a claim.',
  },
  {
    name: 'SIMCO',
    serviceEmail: 'service@simcogroup.com.au',
    ccEmail: 'jenny@simcogroup.com.au',
    portalUrl: 'https://simcogroup.com.au/support',
    phone: '1300 883 888 · 02 8530 7696',
    aliases: ['Simco', 'Simco Group'],
    defaultWarrantyMonths: 24,
    warrantyNotes: '48 months total: the first 24 are parts AND on-site labour, the next 24 are parts only. Listed consumable parts 12. The 24 here is the labour-inclusive period, which is what a service call turns on.',
    notes: 'ATTACH THE SIMCO PICKING SLIP TO EVERY REQUEST.',
  },
  {
    name: 'Skope',
    serviceEmail: 'service.ssa@skopeservices.com.au',
    portalUrl: 'https://booking.mendrhub.com/?tenantid=e32a23e5-8591-4f18-84db-c3dcafadc070&tid=ca54bc84-448c-44d6-8625-60853b6fd8c0',
    phone: '1800 121 535',
    aliases: ['Skope', 'ActiveCore', 'ProSpec', 'Pegasus', 'ReFlex', 'EziCore', 'ITV', 'Irinox', 'Vitamix'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'ActiveCore 60; ProSpec fridges 60 registered; ProSpec freezers, BackBar, Pegasus, ReFlex and EziCore 36 registered; ITV, Irinox, OpenDeck and Ascend 24; Customs 12; Vitamix 36 parts / 12 labour.',
    notes: 'Several ranges only reach their full term if registered.',
  },
  {
    name: 'Stoddart',
    serviceEmail: 'service@stoddart.com.au',
    portalUrl: 'https://customerservice.stoddart.com.au/s/',
    phone: '1300 307 289',
    aliases: ['Stoddart', 'Woodson', 'TurboChef', 'Koldtech', 'Airex', 'Aristarco', 'Giorik', 'Synergy', 'Adande'],
    defaultWarrantyMonths: 12,
    warrantyNotes: 'Stoddart, Woodson, TurboChef and Koldtech generally 12/12. Airex, Aristarco, Giorik, Synergy and eligible Electrolux refrigeration 24/24 subject to registration. Adande 24 labour / 60 selected parts.',
    notes: 'OBTAIN AUTHORISATION BEFORE ANY REPAIR.',
  },
  {
    name: 'Unox',
    serviceEmail: 'service@unoxaustralia.com.au',
    ccEmail: 'info.australia@unox.com',
    portalUrl: 'https://www.unox.com/au_au/support/warranty/-unox-warranty/',
    phone: '03 9876 0803',
    aliases: ['Unox'],
    defaultWarrantyMonths: 12,
    warrantyNotes: 'LONG.Life 12 parts and labour. Eligible LONG.Life4 up to 48 parts / 24 labour; LONG.Life5 up to 60 parts / 24 labour, subject to operating hours and programme conditions.',
    notes: 'A service app is also available.',
  },
  {
    name: 'Uropa / Nisbets',
    serviceEmail: 'warranties@uropa.com.au',
    portalUrl: 'https://booking.mendrhub.com/?tenantid=0d95fb74-2828-43f0-9108-b91c9f874190',
    phone: '1300 225 960 · 02 4648 7887',
    aliases: ['Uropa', 'Nisbets', 'Polar', 'Apuro', 'Sammic', 'Thor', 'Waring', 'Buffalo'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Multi-brand portfolio — confirm by brand and model.',
    notes: 'THE CUSTOMER MUST SUBMIT THE ONLINE FORM THEMSELVES.',
  },
  {
    name: 'Williams Refrigeration',
    serviceEmail: 'customersupport@williamsref.com.au',
    portalUrl: 'https://www.williams-refrigeration.com.au/',
    phone: '03 8787 4747',
    aliases: ['Williams'],
    defaultWarrantyMonths: 24,
    warrantyNotes: 'Self-contained 24 months from the Williams invoice. REMOTE CONDENSER UNITS ARE 12 MONTHS, PARTS ONLY — change the months on a remote unit. Spare parts 3.',
    notes: '',
  },
  {
    name: 'Winterhalter / Classeq',
    serviceEmail: 'service@winterhalter.com.au',
    ccEmail: 'spares@winterhalter.com.au',
    portalUrl: 'https://www.winterhalter.com/au-en/contact-2/',
    phone: '02 9645 3221',
    aliases: ['Winterhalter', 'Classeq'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'Australian terms defer to the Service Call Policy and any proof of extended warranty — confirm from the quotation or invoice.',
    notes: 'Send site, serial, invoice and fault details.',
  },
  {
    name: 'The Good Lady',
    serviceEmail: 'service@thegoodlady.com.au',
    portalUrl: '',
    phone: '',
    aliases: ['The Good Lady', 'Good Lady'],
    defaultWarrantyMonths: null,
    warrantyNotes: 'No reliable public warranty schedule located — request written confirmation against the exact order.',
    notes: 'No public service portal found.',
  },
];

/** What CHES must gather before lodging with any of these desks. */
const CLAIM_CHECKLIST = [
  'Confirm supplier, brand, exact model and serial number.',
  'Attach the customer invoice, supplier invoice or picking slip as required.',
  'Confirm the installation or commissioning date and any warranty registration.',
  'Provide the fault description, photos or video, and any error codes.',
  'Check installation, ventilation, filtration, cleaning and maintenance compliance.',
  'Warn that non-warranty faults, after-hours work, travel, access delays and card pre-authorisation may be chargeable.',
  'Do not arrange an external technician before written supplier authorisation.',
];

module.exports = { SUPPLIERS, CLAIM_CHECKLIST };
